// <auto-generated />
using System;
using BPMeasurementApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPMeasurementApp.Migrations
{
    [DbContext(typeof(BPMeasurementDbContext))]
    [Migration("20241005190108_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPMeasurementApp.Entities.BPMeasurement", b =>
                {
                    b.Property<int>("BPMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BPMeasurementId"));

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("BPMeasurementId");

                    b.ToTable("BPMeasurements");

                    b.HasData(
                        new
                        {
                            BPMeasurementId = 1,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 9, 30, 15, 1, 8, 4, DateTimeKind.Local).AddTicks(1570),
                            Systolic = 120
                        },
                        new
                        {
                            BPMeasurementId = 2,
                            Diastolic = 85,
                            MeasurementDate = new DateTime(2024, 10, 1, 15, 1, 8, 4, DateTimeKind.Local).AddTicks(1680),
                            Systolic = 130
                        },
                        new
                        {
                            BPMeasurementId = 3,
                            Diastolic = 90,
                            MeasurementDate = new DateTime(2024, 10, 2, 15, 1, 8, 4, DateTimeKind.Local).AddTicks(1684),
                            Systolic = 140
                        },
                        new
                        {
                            BPMeasurementId = 4,
                            Diastolic = 75,
                            MeasurementDate = new DateTime(2024, 10, 3, 15, 1, 8, 4, DateTimeKind.Local).AddTicks(1689),
                            Systolic = 110
                        },
                        new
                        {
                            BPMeasurementId = 5,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 10, 4, 15, 1, 8, 4, DateTimeKind.Local).AddTicks(1693),
                            Systolic = 125
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
