// <auto-generated />
using System;
using BPMeasurementApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPMeasurementApp.Migrations
{
    [DbContext(typeof(BPMeasurementDbContext))]
    partial class BPMeasurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPMeasurementApp.Entities.BPMeasurement", b =>
                {
                    b.Property<int>("BPMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BPMeasurementId"));

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("BPMeasurementId");

                    b.HasIndex("PositionId");

                    b.ToTable("BPMeasurements");

                    b.HasData(
                        new
                        {
                            BPMeasurementId = 1,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 9, 30, 15, 3, 43, 40, DateTimeKind.Local).AddTicks(2461),
                            PositionId = "2",
                            Systolic = 120
                        },
                        new
                        {
                            BPMeasurementId = 2,
                            Diastolic = 85,
                            MeasurementDate = new DateTime(2024, 10, 1, 15, 3, 43, 40, DateTimeKind.Local).AddTicks(2589),
                            PositionId = "1",
                            Systolic = 130
                        },
                        new
                        {
                            BPMeasurementId = 3,
                            Diastolic = 90,
                            MeasurementDate = new DateTime(2024, 10, 2, 15, 3, 43, 40, DateTimeKind.Local).AddTicks(2594),
                            PositionId = "3",
                            Systolic = 140
                        },
                        new
                        {
                            BPMeasurementId = 4,
                            Diastolic = 75,
                            MeasurementDate = new DateTime(2024, 10, 3, 15, 3, 43, 40, DateTimeKind.Local).AddTicks(2598),
                            PositionId = "2",
                            Systolic = 110
                        },
                        new
                        {
                            BPMeasurementId = 5,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 10, 4, 15, 3, 43, 40, DateTimeKind.Local).AddTicks(2602),
                            PositionId = "1",
                            Systolic = 125
                        });
                });

            modelBuilder.Entity("BPMeasurementApp.Entities.Position", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = "1",
                            Name = "Standing"
                        },
                        new
                        {
                            PositionId = "2",
                            Name = "Sitting"
                        },
                        new
                        {
                            PositionId = "3",
                            Name = "Lying down"
                        });
                });

            modelBuilder.Entity("BPMeasurementApp.Entities.BPMeasurement", b =>
                {
                    b.HasOne("BPMeasurementApp.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
